# Generated by Django 3.2.10 on 2022-01-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itodb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
            ],
        ),
    ]
