# Generated by Django 3.2.10 on 2022-01-07 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itodb', '0003_object_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itodb.object')),
            ],
        ),
    ]
