# Generated by Django 3.2.10 on 2022-02-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itodb', '0005_stuff_substuff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=40, verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='stuff',
            name='comment',
            field=models.CharField(max_length=40, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='date_purchase',
            field=models.CharField(max_length=40, verbose_name='date_purchase'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='date_transfer',
            field=models.CharField(max_length=40, verbose_name='date_transfer'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='manufacturer',
            field=models.CharField(max_length=40, verbose_name='manufasturer'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='model',
            field=models.CharField(max_length=40, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='object_fact',
            field=models.CharField(max_length=40, verbose_name='object_fact'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='object_target',
            field=models.CharField(max_length=40, verbose_name='object_target'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='seller',
            field=models.CharField(max_length=40, verbose_name='seller'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='serial',
            field=models.CharField(max_length=40, verbose_name='serial'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='type',
            field=models.CharField(max_length=40, verbose_name='type'),
        ),
    ]
