# Generated by Django 3.2.10 on 2022-02-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itodb', '0006_auto_20220216_1545'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Types',
            new_name='Type',
        ),
    ]
