# Generated by Django 3.2.10 on 2022-02-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itodb', '0008_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=40, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=40, verbose_name='')),
            ],
        ),
    ]
