# Generated by Django 3.2.10 on 2022-02-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itodb', '0010_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='manufacturer',
            field=models.CharField(max_length=40, verbose_name='manufacturer'),
        ),
    ]
