# Generated by Django 3.2.10 on 2022-02-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itodb', '0014_alter_stuff_date_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='comment',
            field=models.CharField(blank=True, max_length=40, verbose_name='comment'),
        ),
    ]
