# Generated by Django 3.2.10 on 2022-02-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itodb', '0016_submodel_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submodel',
            name='submodel_name',
            field=models.CharField(max_length=40, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='subtype',
            name='subtype_name',
            field=models.CharField(max_length=40, verbose_name='name'),
        ),
    ]
