# Generated by Django 3.2.10 on 2022-03-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itodb', '0019_stuff_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubStuff',
        ),
    ]
