# Generated by Django 3.2.10 on 2022-03-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itodb', '0021_stuff_subobject_fact'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='note',
            field=models.CharField(blank=True, max_length=500, verbose_name='Notes'),
        ),
    ]
