# Generated by Django 3.2.10 on 2022-04-01 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itodb', '0022_object_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=40, verbose_name='mdoel')),
                ('type', models.CharField(max_length=40, verbose_name='type')),
                ('count', models.CharField(max_length=5, verbose_name='count')),
                ('connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itodb.object')),
            ],
        ),
    ]
