# Generated by Django 3.2.10 on 2022-04-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itodb', '0024_auto_20220401_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='state',
            field=models.CharField(blank=True, max_length=1, verbose_name='State'),
        ),
    ]
