# Generated by Django 3.2.10 on 2022-04-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itodb', '0025_object_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='state',
            field=models.CharField(blank=True, max_length=15, verbose_name='State'),
        ),
    ]
