# Generated by Django 3.2.4 on 2022-05-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itodb', '0026_alter_object_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='referal',
            field=models.CharField(blank=True, max_length=200, verbose_name='referal'),
        ),
    ]
