# Generated by Django 3.2.4 on 2022-05-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itodb', '0028_alter_stuff_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='note',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Notes'),
        ),
    ]
