# Generated by Django 3.2.4 on 2022-06-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itodb', '0029_alter_object_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hystory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('user', models.CharField(max_length=40, verbose_name='user')),
                ('type', models.CharField(max_length=5, verbose_name='type')),
                ('serial', models.CharField(max_length=30, verbose_name='serial')),
                ('event', models.CharField(max_length=200, verbose_name='event')),
            ],
        ),
    ]
