# Generated by Django 3.2.4 on 2022-06-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itodb', '0031_alter_hystory_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hystory',
            name='type',
        ),
    ]
