# Generated by Django 3.2.4 on 2022-06-16 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itodb', '0032_remove_hystory_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hystory',
            new_name='History',
        ),
    ]
