# Generated by Django 3.2.4 on 2022-06-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itodb', '0034_alter_history_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.CharField(blank=True, max_length=40, verbose_name='user'),
        ),
    ]
