# Generated by Django 3.2.4 on 2022-06-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itodb', '0035_alter_history_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='serial',
            field=models.CharField(max_length=50, verbose_name='serial'),
        ),
    ]
