# Generated by Django 3.2.4 on 2022-06-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itodb', '0038_alter_history_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='event',
            field=models.CharField(max_length=500, verbose_name='event'),
        ),
    ]
